#!/bin/bash
#
# OpenClaw Setup Script
#
# One-command setup for OpenClaw local development with NEON-SOUL integration.
#
# Usage:
#   ./scripts/setup-openclaw.sh [options]
#
# Options:
#   --skip-docker    Skip Docker Compose startup
#   --reset          Reset workspace (WARNING: destroys existing data)
#   --help           Show this help message
#
# Prerequisites:
#   - Docker and Docker Compose installed
#   - API key (Anthropic or OpenAI)
#
# What this script does:
#   1. Checks prerequisites (Docker, docker-compose)
#   2. Creates OpenClaw workspace directory if missing
#   3. Initializes workspace structure (memory directories)
#   4. Copies .env.example to .env if not exists
#   5. Starts OpenClaw via Docker Compose
#   6. Waits for health check
#   7. Displays status and next steps
#
# Output:
#   - ~/.openclaw/workspace/ directory structure
#   - docker/.env file (from .env.example)
#   - Running OpenClaw container
#

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
DOCKER_DIR="$PROJECT_DIR/docker"
WORKSPACE_DIR="${OPENCLAW_WORKSPACE:-$HOME/.openclaw/workspace}"
SKIP_DOCKER=false
RESET=false

# Print functions
info() { echo -e "${BLUE}[INFO]${NC} $1"; }
success() { echo -e "${GREEN}[OK]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

# Help message
show_help() {
    head -35 "$0" | tail -30
    exit 0
}

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --skip-docker) SKIP_DOCKER=true; shift ;;
        --reset) RESET=true; shift ;;
        --help|-h) show_help ;;
        *) error "Unknown option: $1" ;;
    esac
done

echo ""
echo "🔮 NEON-SOUL + OpenClaw Setup"
echo "=============================="
echo ""

# Step 1: Check prerequisites
info "Checking prerequisites..."

if ! command -v docker &> /dev/null; then
    error "Docker is not installed. Please install Docker Desktop: https://docker.com/get-started"
fi
success "Docker installed"

if ! docker compose version &> /dev/null && ! command -v docker-compose &> /dev/null; then
    error "Docker Compose is not installed. Please install Docker Compose."
fi
success "Docker Compose installed"

# Step 2: Handle reset
if [ "$RESET" = true ]; then
    warn "Reset requested - this will destroy existing workspace data!"

    # IM-1 FIX: Validate workspace path before rm -rf
    # Prevent accidental deletion of root, home, or non-openclaw directories
    RESOLVED_WORKSPACE=$(realpath "$WORKSPACE_DIR" 2>/dev/null || echo "$WORKSPACE_DIR")

    if [ -z "$RESOLVED_WORKSPACE" ] || [ "$RESOLVED_WORKSPACE" = "/" ] || [ "$RESOLVED_WORKSPACE" = "$HOME" ]; then
        error "WORKSPACE_DIR resolved to unsafe path: '$RESOLVED_WORKSPACE'. Aborting reset."
    fi

    if [[ ! "$RESOLVED_WORKSPACE" =~ \.openclaw ]]; then
        error "WORKSPACE_DIR must contain '.openclaw' in path for safety. Got: '$RESOLVED_WORKSPACE'"
    fi

    warn "Will delete: $RESOLVED_WORKSPACE"
    read -p "Are you sure? (type 'yes' to confirm): " confirm
    if [ "$confirm" = "yes" ]; then
        info "Resetting workspace..."
        rm -rf "$RESOLVED_WORKSPACE"
        success "Workspace reset"
    else
        info "Reset cancelled"
    fi
fi

# Step 3: Create workspace directory structure
info "Setting up workspace at $WORKSPACE_DIR..."

# Create main workspace directory
mkdir -p "$WORKSPACE_DIR"

# Create memory subdirectories (OpenClaw structure)
MEMORY_DIRS=(
    "memory/diary"
    "memory/experiences"
    "memory/goals"
    "memory/knowledge"
    "memory/relationships"
    "memory/preferences"
)

for dir in "${MEMORY_DIRS[@]}"; do
    mkdir -p "$WORKSPACE_DIR/$dir"
done
success "Workspace directories created"

# Create placeholder files if workspace is new
if [ ! -f "$WORKSPACE_DIR/SOUL.md" ]; then
    info "Initializing workspace files..."

    cat > "$WORKSPACE_DIR/SOUL.md" << 'EOF'
# SOUL.md

This file will be populated by NEON-SOUL after bootstrap.

## Current State

Awaiting initial signal extraction and axiom synthesis.

---

*Generated by NEON-SOUL setup script*
EOF

    cat > "$WORKSPACE_DIR/USER.md" << 'EOF'
# USER.md

User profile and preferences.

## Identity

(To be discovered through interview and memory analysis)

---

*Generated by NEON-SOUL setup script*
EOF

    success "Placeholder files created"
fi

# Step 4: Setup environment file
info "Configuring environment..."

if [ ! -f "$DOCKER_DIR/.env" ]; then
    if [ -f "$DOCKER_DIR/.env.example" ]; then
        cp "$DOCKER_DIR/.env.example" "$DOCKER_DIR/.env"
        warn "Created .env from .env.example - please edit with your API keys"
        warn "  vim $DOCKER_DIR/.env"
    else
        error ".env.example not found in $DOCKER_DIR"
    fi
else
    success "Environment file exists"
fi

# Check if API key is configured
if grep -q "sk-ant-your-key-here" "$DOCKER_DIR/.env" 2>/dev/null; then
    warn "API key not configured in .env - please add your Anthropic API key"
    warn "  vim $DOCKER_DIR/.env"
fi

# MN-7 FIX: Validate API key format if present
ANTHROPIC_KEY=$(grep "^ANTHROPIC_API_KEY=" "$DOCKER_DIR/.env" 2>/dev/null | cut -d'=' -f2)
if [ -n "$ANTHROPIC_KEY" ] && [ "$ANTHROPIC_KEY" != "sk-ant-your-key-here" ]; then
    if [[ ! "$ANTHROPIC_KEY" =~ ^sk-ant- ]]; then
        warn "ANTHROPIC_API_KEY doesn't match expected format (should start with 'sk-ant-')"
    fi
fi

OPENAI_KEY=$(grep "^OPENAI_API_KEY=" "$DOCKER_DIR/.env" 2>/dev/null | cut -d'=' -f2)
if [ -n "$OPENAI_KEY" ]; then
    if [[ ! "$OPENAI_KEY" =~ ^sk- ]]; then
        warn "OPENAI_API_KEY doesn't match expected format (should start with 'sk-')"
    fi
fi

# Step 5: Start Docker Compose
if [ "$SKIP_DOCKER" = true ]; then
    info "Skipping Docker startup (--skip-docker)"
else
    info "Starting OpenClaw via Docker Compose..."

    cd "$DOCKER_DIR"

    # Check if already running
    if docker compose ps 2>/dev/null | grep -q "openclaw-dev"; then
        info "OpenClaw container already running"
    else
        docker compose up -d

        info "Waiting for OpenClaw to start..."
        sleep 5

        # Simple health check
        if docker compose ps | grep -q "Up"; then
            success "OpenClaw started"
        else
            warn "OpenClaw may not have started correctly. Check logs:"
            warn "  docker compose logs openclaw"
        fi
    fi
fi

# Step 6: Display status
echo ""
echo "=============================="
echo "🎉 Setup Complete!"
echo "=============================="
echo ""
echo "Workspace: $WORKSPACE_DIR"
echo ""
echo "Directory structure:"
echo "  ~/.openclaw/workspace/"
echo "  ├── SOUL.md              # AI identity (updated by NEON-SOUL)"
echo "  ├── USER.md              # User profile"
echo "  └── memory/"
echo "      ├── diary/           # Journal entries"
echo "      ├── experiences/     # Event memories"
echo "      ├── goals/           # Aspirations"
echo "      ├── knowledge/       # Learned facts"
echo "      ├── relationships/   # People & connections"
echo "      └── preferences/     # Likes, dislikes"
echo ""

if [ "$SKIP_DOCKER" != true ]; then
    echo "Services:"
    echo "  Web UI:  http://localhost:3000"
    echo "  API:     http://localhost:8080"
    echo ""
    echo "Commands:"
    echo "  docker compose logs -f openclaw  # View logs"
    echo "  docker compose down              # Stop services"
    echo ""
fi

echo "Next steps:"
echo "  1. Start Ollama: docker compose -f docker/docker-compose.ollama.yml up -d"
echo "  2. Pull model: docker exec neon-soul-ollama ollama pull llama3"
echo "  3. Create memory files in ~/.openclaw/workspace/memory/"
echo "  4. Run: npx tsx src/commands/synthesize.ts --dry-run"
echo ""
